server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      
      routes:
        # 1. Todo lo de identidad, perfiles, roles y login se va a MS-USUARIOS
        - id: usuarios-route
          uri: lb://MS-USUARIOS
          predicates:
            - Path=/api/usuarios/**,/api/roles/**,/api/auth/**

        # 2. Todo lo de tarjetas y finanzas se va a MS-CLIENTES
        - id: clientes-route
          uri: lb://MS-CLIENTES
          predicates:
            - Path=/api/clientes/**

        # 3. Todo lo de proveedores y documentos se va a MS-PROVEEDORES
        - id: proveedores-route
          uri: lb://MS-PROVEEDORES
          predicates:
            - Path=/api/proveedores/**

        # ¡NUEVO! 4. Todo lo de catálogo, stock y categorías se va a MS-PRODUCTOS
        - id: productos-route
          uri: lb://MS-PRODUCTOS  # <-- OJO: Debe ser IGUAL al spring.application.name de tu ms_productos
          predicates:
            - Path=/api/productos/**
          
        - id: ventas-route
          uri: lb://MS-VENTA  # <-- Asegúrate de que tu ms_ventas se llame exactamente así en su application.yml
          predicates:
            - Path=/api/ventas/**
            # 6. Todo lo de reclamos y disputas se va a MS-TICKET
        - id: tickets-route
          uri: lb://MS-TICKET  # <-- Revisa que coincida con el nombre en el yml de tickets
          predicates:
            - Path=/api/tickets/**
        # 7. Todo lo de correos y alertas se va a MS-NOTIFICACION
        - id: notificacion-route
          uri: lb://MS-NOTIFICACION
          predicates:
            - Path=/api/notificaciones/**

# ==========================================
# CONFIGURACIÓN DE EUREKA
# ==========================================
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true